-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 15:18:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `login` ;

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login` DEFAULT CHARACTER SET utf8mb4 ;
USE `login` ;

-- -----------------------------------------------------
-- Table `login`.`tb_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`tb_ativo` (
  `id_ativo` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_ativo` INT(11) NOT NULL,
  `descricao_ativo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ativo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `login`.`tb_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`tb_perfil` (
  `id_perfil` INT(1) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `cod_perfil` VARCHAR(45) NOT NULL,
  `no_perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `login`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`tb_usuario` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(200) NOT NULL,
  `email` VARCHAR(105) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `Nome` VARCHAR(105) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `tb_perfil_id_perfil` INT(1) UNSIGNED ZEROFILL NOT NULL,
  `tb_ativo_id_ativo` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_tb_usuario_tb_perfil_idx` (`tb_perfil_id_perfil` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_ativo1_idx` (`tb_ativo_id_ativo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_ativo1`
    FOREIGN KEY (`tb_ativo_id_ativo`)
    REFERENCES `login`.`tb_ativo` (`id_ativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_tb_perfil`
    FOREIGN KEY (`tb_perfil_id_perfil`)
    REFERENCES `login`.`tb_perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 180
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
